name: hillandfriend
channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  - python=3.10
  - pip
  - llvm-openmp

  - numpy
  - pandas
  - scipy
  - scikit-learn
  - seaborn
  - matplotlib
  - xgboost

  - jupyterlab
  - notebook
  - ipykernel
  - ipywidgets

  - requests
  - pyyaml
  - pillow
  - beautifulsoup4

  - pytorch=2.5
  - torchvision
  - torchaudio